# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DownloadList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DownloadList
  #网络
  pod 'AFNetworking', '3.1.0’
  #弹出框
  pod 'MBProgressHUD', '0.9.2'
  pod 'SVProgressHUD'
  #刷新
  pod 'MJRefresh', '3.1.7'
  #图片缓存
  pod 'SDWebImage'
  #加压zip文件
  pod 'SSZipArchive', '~> 2.1.0'
end
